config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'statistics#index'

  namespace :api, :defaults => { :format => :json } do
    resources :surveys do
      collection do
        get :completed
        get :profile
      end
      get :is_active, on: :member
    end
    resources :auth do
      post :login, on: :collection
      post :logout, on: :collection
      post :facebook, on: :collection
      post :password_reset, on: :collection
    end
    resources :profile do
      patch :change, on: :collection
      post :avatar, on: :collection
      post :refer_a_friend, on: :collection
    end
    resources :mappings do
      get :masterdata, on: :collection
    end
    resources :register
    resources :push_notification_credentials
    resources :faqs
    resources :quick_polls do
      get :results, on: :member
      get :completed, on: :collection
    end
    resources :geofences do
      post :logs, on: :collection
    end
    resources :log
    resources :vpn_studies do
      collection do
        get :active
        get :completed
        get :cancelled
        get :connected
      end
      member do
        get :is_active
      end
    end
    resources :vpn_study_credentials do
      post  :download, on: :collection
      post  :activate, on: :collection
      post  :disconnect, on: :collection
      post  :complete, on: :collection
      get   :completed, on: :collection
    end
    resources :statistics do
      get :panelists, on: :collection
    end
    resources :device_metadata
  end

  resources :panelists do
    get :export, on: :collection
    get :sync_last_accessed, on: :collection
    get :autocomplete_panelist_email, on: :collection
    resources :push_notification_credentials do
      get :test, on: :member
    end
  end
  resources :settings
  resources :profile_variables
  resources :users
  resources :master_data_descriptions do
    get :reload, on: :collection
  end
  resources :mail_templates do
    get :reload, on: :collection
  end
  resources :survey_categories
  resources :surveys do
    get   :reload, on: :collection
    post  :send_notifications, on: :member
    get   :show_push_notification_form, on: :member
  end
  resources :profile_surveys
  resources :faqs
  resources :quick_polls do
    get :send_notifications, on: :member
    get :autocomplete_quick_poll_title, on: :collection
  end
  resources :quick_poll_responses do
    get :export, on: :collection
  end
  resources :geofences do
    get :export, on: :collection
    get :info, on: :collection
  end
  resources :geofence_logs do
    post  :export, on: :collection
    get   :panelist_logs, on: :collection
  end
  resources :geofence_groups do
    get   :reload_apps, on: :collection
    get   :map, on: :member
    get   :export, on: :collection
    post  :status_update, on: :member
    get :autocomplete_geofence_group_name, on: :collection
  end
  resources :samples do
    get :reload, on: :collection
  end
  resources :questback_groups do
    get :reload, on: :collection
    get :search, on: :collection
    get :autocomplete_questback_group_name, on: :collection
  end
  resources :geofence_collections do
    post  :import, on: :collection
    get   :upload, on: :collection
  end
  resources :quick_poll_stats do
    get :update_stats, on: :collection
  end
  resources :vpn_studies do
    member do
      get :send_notifications
      get :reload_data
      get :deactivate
    end
    get :autocomplete_vpn_study_name, on: :collection
  end
  resources :usage_study_access_logs do
    post :export, on: :collection
  end
  resources :usage_study_users do
    get :access_logs, on: :member
    get :export, on: :collection
  end
  resources :router_managements do
    post  :disconnect, on: :collection
    post  :sync, on: :collection
    get   :convert_ip_address, on: :collection
  end
  resources :ssl_decryption_hosts do
    post :sync, on: :collection
  end
  resources :vpn_bandwidth_usages do
    get :export, on: :collection
  end
  resources :device_metadata do
    get :panelist, on: :collection
  end
  resources :log_exports do
    get :export, on: :collection
    get :download, on: :member
  end
  resources :geofence_log_exports do
    get :download, on: :member
  end
  resources :vpn_managements do
    get :vpn_speed_test, on: :collection
  end
  resources :geofence_uploads do
    get :export_template, on: :collection
  end
  resources :bart_settings do
    get :export_csv_file, on: :collection
  end
  resources :panelist_stats do
  end

  resources :admin
  resources :push_notification_logs
  resources :statistics
  resources :panelist_sync_logs
  resources :vpn_routes
  resources :decrypt_hosts
  resources :vpn_page_monitorings
  resources :vpn_page_monitoring_results
  resources :vpn_study_credentials
  resources :logs
  resources :bart_audit_logs

  get '*path' => redirect('/')








end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :survey
  has_and_belongs_to_many :panelists
  scope :ordered,                     -> { order(created_at: :asc) }

  def send_notification_to_panelists(survey_id:)
    panelists.each do |panelist|
      panelist.send_device_notification(survey_id: survey_id)
    end
  end

  def self.search(search)
  where("title LIKE ?", "%#{search}%") 
  end

end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController

  before_action :authenticate_user!
  before_action :find_delayed_job, only: [:index]

  def index
    @samples = Sample.search(params[:search]).ordered.paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.js
    @reload_in_progress = @delayed_job.size != 0
    @reload_status      = @reload_in_progress ? @delayed_job.first.status_text : ""
  end
end

  def show
    @sample = Sample.find(params[:id])
  end

  def reload
    params[:active] ? ActiveSamplesReloadJob.perform_later : SamplesReloadJob.perform_later
    respond_to do |format|
      format.js
    end
  end

  private

  def find_delayed_job
    @delayed_job =  params[:active] ? Delayed::Job.where("handler like ?", "%#{ActiveSamplesReloadJob.to_s}%") : Delayed::Job.where("handler like ?", "%#{SamplesReloadJob.to_s}%")
  end

end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_tabs.html.erb
<div class="page-tabs">
	<ul class="nav nav-tabs" role="tablist">

	    <li>
			<%= link_to "Admin", admin_index_path %>
		</li>

		<% if active == :samples %><li class="active"><% else %><li><% end %>
			<%= link_to "Samples", samples_path %>
		</li>

		<% if active == :sample %>
			<li class="active">
				<%= link_to "Sample", sample_path %>
			</li>
		<% end %>

	</ul>
</div>

app/views/samples/index.html.erb
<%= render "tabs", :active => :samples %>

<br>

		<%= link_to "Reload All Samples", reload_samples_path, :remote => true, :class => "btn btn-default", :id => "reload-button", :style => "display:#{@reload_in_progress ? 'none' : 'inline-block'};" %>
		<%= link_to "Reload Active Samples", reload_samples_path(active: true), :remote => true, :class => "btn btn-info", :id => "reload-active-button", :style => "display:#{@reload_in_progress ? 'none' : 'inline-block'};" %>
		<p id="reloading-text" <%= @reload_in_progress ? "" : "hidden"%>>Reloading QuestBack Samples...</p>
		<p><%= @reload_in_progress ? @reload_status : "" %></p>

		<br>

		<%= form_tag(samples_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Samples" %>
    <%= submit_tag "Search", :title => nil %>
<% end %>


<br>

		<table class="table">
			<thead>
				<tr>
					<th>SampleID</th>
					<th>SurveyID</th>
					<th>Title</th>
					<th>Description</th>
				</tr>
			</thead>
			<tbody>
				<% @samples.each do |sample| %>
					<tr>
						<td><%= link_to sample.sample_id, sample %></td>
						<td><%= sample.survey != nil ? link_to(sample.survey.survey_id, sample.survey) : "Needs Surveys Refresh" %></td>
						<td><%= sample.title %></td>
						<td><%= sample.description %></td>
					</tr>
				<% end %>
			</tbody>
		</table>


<%= will_paginate @samples %>

app/views/samples/reload.js.erb
$("#reloading-text").show();
$("#reload-button").hide();
$("#reload-active-button").hide();

app/views/samples/show.html.erb
<%= render "tabs", :active => :sample %>

<h1>Sample</h1>

<div class="list-group">

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Sample ID
		</div>
		<div class="list-group-item-text">
			<%= @sample.sample_id %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Survey ID
		</div>
		<div class="list-group-item-text">
			<%= @sample.survey != nil ? link_to(@sample.survey.survey_id, @sample.survey) : "Needs Surveys Refresh" %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Title
		</div>
		<div class="list-group-item-text">
			<%= @sample.title %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Description
		</div>
		<div class="list-group-item-text">
			<%= @sample.description %>
		</div>
  </div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Panelists
		</div>
    <div class="list-group-item-text">
      <% if @sample.panelists.any? %>
        <% @sample.panelists.each do |sample_panelist| %>
          <ul>
            <li><%= link_to sample_panelist.email, panelist_path(sample_panelist) %></li>
          </ul>
        <% end %>
      <% else %>
        No panelist listed.
      <% end %>
		</div>
  </div>

</div>