config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'statistics#index'

  namespace :api, :defaults => { :format => :json } do
    resources :surveys do
      collection do
        get :completed
        get :profile
      end
      get :is_active, on: :member
    end
    resources :auth do
      post :login, on: :collection
      post :logout, on: :collection
      post :facebook, on: :collection
      post :password_reset, on: :collection
    end
    resources :profile do
      patch :change, on: :collection
      post :avatar, on: :collection
      post :refer_a_friend, on: :collection
    end
    resources :mappings do
      get :masterdata, on: :collection
    end
    resources :register
    resources :push_notification_credentials
    resources :faqs
    resources :quick_polls do
      get :results, on: :member
      get :completed, on: :collection
    end
    resources :geofences do
      post :logs, on: :collection
    end
    resources :log
    resources :vpn_studies do
      collection do
        get :active
        get :completed
        get :cancelled
        get :connected
      end
      member do
        get :is_active
      end
    end
    resources :vpn_study_credentials do
      post  :download, on: :collection
      post  :activate, on: :collection
      post  :disconnect, on: :collection
      post  :complete, on: :collection
      get   :completed, on: :collection
    end
    resources :statistics do
      get :panelists, on: :collection
    end
    resources :device_metadata
  end

  resources :panelists do
    get :export, on: :collection
    get :sync_last_accessed, on: :collection
    get :autocomplete_panelist_email, on: :collection
    resources :push_notification_credentials do
      get :test, on: :member
    end
  end
  resources :settings
  resources :profile_variables
  resources :users
  resources :master_data_descriptions do
    get :reload, on: :collection
  end
  resources :mail_templates do
    get :reload, on: :collection
  end
  resources :survey_categories
  resources :surveys do
    get   :reload, on: :collection
    post  :send_notifications, on: :member
    get   :show_push_notification_form, on: :member
  end
  resources :profile_surveys
  resources :faqs
  resources :quick_polls do
    get :send_notifications, on: :member
    get :autocomplete_quick_poll_title, on: :collection
  end
  resources :quick_poll_responses do
    get :export, on: :collection
  end
  resources :geofences do
    get :export, on: :collection
    get :info, on: :collection
  end
  resources :geofence_logs do
    post  :export, on: :collection
    get   :panelist_logs, on: :collection
  end
  resources :geofence_groups do
    get   :reload_apps, on: :collection
    get   :map, on: :member
    get   :export, on: :collection
    post  :status_update, on: :member
    get :autocomplete_geofence_group_name, on: :collection
  end
  resources :samples do
    get :reload, on: :collection
  end
  resources :questback_groups do
    get :reload, on: :collection
    get :search, on: :collection
    get :autocomplete_questback_group_name, on: :collection
  end
  resources :geofence_collections do
    post  :import, on: :collection
    get   :upload, on: :collection
  end
  resources :quick_poll_stats do
    get :update_stats, on: :collection
  end
  resources :vpn_studies do
    member do
      get :send_notifications
      get :reload_data
      get :deactivate
    end
    get :autocomplete_vpn_study_name, on: :collection
  end
  resources :usage_study_access_logs do
    post :export, on: :collection
  end
  resources :usage_study_users do
    get :access_logs, on: :member
    get :export, on: :collection
  end
  resources :router_managements do
    post  :disconnect, on: :collection
    post  :sync, on: :collection
    get   :convert_ip_address, on: :collection
  end
  resources :ssl_decryption_hosts do
    post :sync, on: :collection
  end
  resources :vpn_bandwidth_usages do
    get :export, on: :collection
  end
  resources :device_metadata do
    get :panelist, on: :collection
  end
  resources :log_exports do
    get :export, on: :collection
    get :download, on: :member
  end
  resources :geofence_log_exports do
    get :download, on: :member
  end
  resources :vpn_managements do
    get :vpn_speed_test, on: :collection
  end
  resources :geofence_uploads do
    get :export_template, on: :collection
  end
  resources :bart_settings do
    get :export_csv_file, on: :collection
  end
  resources :panelist_stats do
  end

  resources :admin
  resources :push_notification_logs
  resources :statistics
  resources :panelist_sync_logs
  resources :vpn_routes
  resources :decrypt_hosts
  resources :vpn_page_monitorings
  resources :vpn_page_monitoring_results
  resources :vpn_study_credentials
  resources :logs
  resources :bart_audit_logs

  get '*path' => redirect('/')








end

app/models/survey.rb
class Survey < ActiveRecord::Base
  include UrlBuilder
  include Notifier
  include Searchable
  belongs_to :survey_category
  has_many :samples

  scope :active_and_questback_active, -> { where(active: true, questback_status: "ACTIVE") }
  scope :with_duration,               -> { where.not(duration: [nil, ""]) }
  scope :without_duration,            -> { where(duration: [nil, ""]) }
  scope :ordered,                     -> { order(registration_survey: :desc, start_time: :desc) }
  scope :ordered_by_title,            -> { order(title: :asc) }

  def self.search(search)
  where("title LIKE ?", "%#{search}%") 
  end

  def is_active?
    active? && questback_status.eql?("ACTIVE")
  end

  def to_s
    title
  end

  def get_panelist_url(panelist, geofence_id: nil)
    panelist_url = "syid=#{self.survey_id}&pcode=#{panelist.external_auth_panelist_code}&b=#{panelist.id}"

    UrlBuilder::build_url(Setting.first.qb_hostname, "/gto.php", panelist_url)
  end

  def is_active_and_questback_active?
    active? && questback_status.eql?("ACTIVE")
  end

end

app/controllers/api/surveys_controller.rb
class Api::SurveysController < Api::ApiController
  before_action :initialize_questback, :initialize_response
  before_action :find_survey, only: [:is_active]

  include DataDescription

  def index
    # curl -H "Content-Type: application/json" -H "Token: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa" localhost:3000/api/surveys

    qb_surveys    = @qb.get_surveys
    qb_survey_ids = qb_surveys.map{ |qb_survey| qb_survey["id"] }
    surveys       = Survey.active_and_questback_active.ordered.where(survey_id: qb_survey_ids)
    surveys       = surveys.map{ |survey| survey_data(survey, completed: false, qb_surveys: qb_surveys) }

    @response[:surveys] = surveys
    render :json => @response
  end

  def completed
    # curl -H "Content-Type: application/json" -H "Token: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa" localhost:3000/api/surveys/completed

    qb_completed_surveys    = @qb.get_completed_surveys
    qb_completed_survey_ids = qb_completed_surveys.map{ |qb_completed_survey| qb_completed_survey["surveyId"] }
    completed_surveys       = Survey.ordered.where(survey_id: qb_completed_survey_ids)
    completed_surveys       = completed_surveys.map{ |completed_survey| survey_data(completed_survey, completed: true) }

    @response[:completed_surveys] = completed_surveys
    render :json => @response
  end

  def profile
    # curl -H "Content-Type: application/json" -H "Token: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa" localhost:3000/api/surveys/profile

    survey_list_ids = @qb.get_completed_surveys.map{ |survey| survey['surveyId'] }

    profile_surveys = []
    ProfileSurvey.all.each do |profile_survey|
      unless survey_list_ids.include?(profile_survey.survey.survey_id)
        profile_surveys << profile_survey_data(profile_survey)
      end
    end

    @response[:profile_surveys] = profile_surveys
    render :json => @response
  end

  def is_active
    @response[:survey].merge!(active: false, message: 'Survey not found.') if @survey.nil?
    @response[:survey].merge!(active: @survey.is_active?) if @survey
    render json: @response
  end

  private

  def initialize_questback
    @qb = ::Questback.new(@panelist.email)
  end

  def initialize_response
    @response = {}
  end

  def find_survey
    @survey   =  Survey.find_by_survey_id params[:id]
    @response = { survey: { success: true } }
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_action :authenticate_user!
  before_action :find_delayed_job, only: [:index]
  before_action :find_survey, except: [:index, :reload]
  autocomplete :survey, :title, extra_data: [:id], full: true, limit: 100

  def index
    @surveys = Survey.search(params[:search]).ordered.paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.js
    @reload_in_progress = @delayed_job.size != 0
    @reload_status      = @reload_in_progress ? @delayed_job.first.status_text : ""

    @survey_active = Survey.where(questback_status: "ACTIVE")
    @survey_generated = Survey.where(questback_status: "GENERATED")
    @survey_archived = Survey.where(questback_status: "ARCHIVED")
    @survey_closing = Survey.where(questback_status: "CLOSING")
    @survey_finished = Survey.where(questback_status: "FINISHED")
  end
end

  def show
  end

  def edit
  end

  def update
    if @survey.update(surveys_params)
      redirect_to @survey
    else
      render 'edit'
    end
  end

  def reload
    params[:active].eql?("true") ? SurveysReloadJob.perform_later(active: true) : SurveysReloadJob.perform_later
    respond_to do |format|
      format.html { redirect_to setting_path(Setting.first) }
      format.js
    end
  end

  def send_notifications
    if @survey
      params[:sample_ids].each do |sample_id|
        SurveySendNotificationsJob.perform_later(survey_id: @survey.survey_id, sample_id: sample_id)
      end
      create_survey_send_notification_log
    end
    redirect_to surveys_path, notice: "You've successfully sent push notification."
  end

  def show_push_notification_form
    @samples = @survey.samples
    render(partial: 'send_push_notification_form', locals: { survey: @survey }, layout: false)
  end

  private

    def surveys_params
      params.require(:survey).permit(
        :survey_id,
        :survey_category_id,
        :duration,
        :active,
        :registration_survey
      )
    end

    def find_delayed_job
      @delayed_job = Delayed::Job.where("handler like ?", "%#{SurveysReloadJob.to_s}%")
    end

    def find_survey
      @survey = Survey.find(params[:id])
    end

    def create_survey_send_notification_log
      push_notification_log_params = {
        survey_id: params[:id],
        sample_ids: params[:sample_ids]
      }
      current_user.push_notification_logs.create(push_notification_log_params)
    end

    def verify_filter_params
      @filter_status = params[:filter] ? params[:filter][:status].to_sym : :all
    end

end

app/helpers/api/surveys_helper.rb
module Api::SurveysHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper

  def survey_collection
    Survey.ordered_by_title.map{ |survey| [survey.title, survey.id] }
  end
end

app/views/surveys/_form.html.erb
<%= form_for @survey do |form| %>

	<%= render "layouts/crud_error", :errorable => @survey %>

	<div class="list-group">

		<div class="list-group-item">
			<div class="list-group-item-heading text-muted">
				<%= form.label :duration %>
			</div>
			<div class="list-group-item-text">
				<%= form.text_field :duration, :class => "form-control" %>
			</div>
		</div>

		<div class="list-group-item">
			<div class="list-group-item-heading text-muted">
				<%= form.label :survey_category %>
			</div>
      <div class="list-group-item-text">
        <%= form.select :survey_category_id, options_for_select(survey_category_collection, selected_survey_category) %>
			</div>
		</div>

		<div class="list-group-item">
			<div class="list-group-item-heading text-muted">
				<%= form.label :active %>
			</div>
			<div class="list-group-item-text">
				<%= form.check_box :active %>
			</div>
		</div>

		<div class="list-group-item">
			<div class="list-group-item-heading text-muted">
				<%= form.label :registration_survey? %>
			</div>
			<div class="list-group-item-text">
				<%= form.check_box :registration_survey %>
			</div>
		</div>

		<div class="list-group-item">
			<%= form.submit :class => "btn btn-default" %>
		</div>

	</div>

<% end %>

app/views/surveys/_send_push_notification_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title" id="ajaxModalLabel">Notify <%= @survey.title %></h4>
</div>
<% if @samples.any? %>
  <%= form_for "send_notification", url: send_notifications_survey_path(@survey) do |form| %>
    <div class='modal-body'>
      <% @samples.each do |sample| %>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= check_box_tag "sample_ids[]", sample.id %>
              <%= form.label sample.title  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class='modal-footer'>
      <%= form.submit "Send Notification", class: 'btn btn-success' %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  <% end %>
<% else %>
  <div class='modal-body'>
    <strong>No Sample Panelists for this Survey<strong>
  </div>
  <div class='modal-footer'>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/surveys/_table.html.erb
<b>Filter Status:</b>
<div id="content">
    <ul id="tabs" class="nav nav-tabs filter-tab" data-tabs="tabs">
    	<li class="active"><a href="#all" data-toggle="tab">All</a></li>
        <li><a href="#active" data-toggle="tab">Active</a></li>
        <li><a href="#generated" data-toggle="tab">Generated</a></li>
        <li><a href="#archived" data-toggle="tab">Archived</a></li>
        <li><a href="#closing" data-toggle="tab">Closing</a></li>
        <li><a href="#finished" data-toggle="tab">Finished</a></li>
    </ul>

    <br>

    <div id="my-tab-content" class="tab-content">

    <div class="tab-pane active" id="all">
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>QuestBackID</th>
				<th>Category</th>
				<th>Duration</th>
				<th>Status</th>
				<th>Active</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @surveys.each do |survey| %>
				<tr>
					<td><%= link_to survey.title, survey %></td>
					<td><%= survey.survey_id %></td>
					<td>
						<% if survey.survey_category == nil %>
							UNASSIGNED
						<% else %>
							<%= survey.survey_category.name %>
							<div style="width:100px; height:20px; background-color:<%= survey.survey_category.color %>">&nbsp;</div>
							<% end %>
					</td>
					<td><%= survey.duration %></td>
					<td><%= survey.questback_status %></td>
					<td><%= survey.active ? '<i class="fa fa-check fa-fw" style="color:#00FF00"></i>'.html_safe : '<i class="fa fa-close fa-fw" style="color:#FF0000"></i>'.html_safe %></td>
					<td>
						<p><%= link_to "Edit", edit_survey_path(survey), :class => "btn btn-info actions" %></p>
						<% if survey.survey_category != nil  && survey.questback_status.downcase == "active" %>
							<p><%= link_to "Send Push Notification", "#", :class => "btn btn-success actions", onclick: "showPushNotificationForm({ title: '#{survey.title}', id: #{survey.id} });" %></p>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<%= will_paginate @surveys %>

        </div>

        <div class="tab-pane" id="active">
            	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>QuestBackID</th>
				<th>Category</th>
				<th>Duration</th>
				<th>Status</th>
				<th>Active</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @survey_active.each do |survey| %>
				<tr>
					<td><%= link_to survey.title, survey %></td>
					<td><%= survey.survey_id %></td>
					<td>
						<% if survey.survey_category == nil %>
							UNASSIGNED
						<% else %>
							<%= survey.survey_category.name %>
							<div style="width:100px; height:20px; background-color:<%= survey.survey_category.color %>">&nbsp;</div>
							<% end %>
					</td>
					<td><%= survey.duration %></td>
					<td><%= survey.questback_status %></td>
					<td><%= survey.active ? '<i class="fa fa-check fa-fw" style="color:#00FF00"></i>'.html_safe : '<i class="fa fa-close fa-fw" style="color:#FF0000"></i>'.html_safe %></td>
					<td>
						<p><%= link_to "Edit", edit_survey_path(survey), :class => "btn btn-info actions" %></p>
						<% if survey.survey_category != nil  && survey.questback_status.downcase == "active" %>
							<p><%= link_to "Send Push Notification", "#", :class => "btn btn-success actions", onclick: "showPushNotificationForm({ title: '#{survey.title}', id: #{survey.id} });" %></p>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
        </div>

        <div class="tab-pane" id="generated">
<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>QuestBackID</th>
				<th>Category</th>
				<th>Duration</th>
				<th>Status</th>
				<th>Active</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @survey_generated.each do |survey| %>
				<tr>
					<td><%= link_to survey.title, survey %></td>
					<td><%= survey.survey_id %></td>
					<td>
						<% if survey.survey_category == nil %>
							UNASSIGNED
						<% else %>
							<%= survey.survey_category.name %>
							<div style="width:100px; height:20px; background-color:<%= survey.survey_category.color %>">&nbsp;</div>
							<% end %>
					</td>
					<td><%= survey.duration %></td>
					<td><%= survey.questback_status %></td>
					<td><%= survey.active ? '<i class="fa fa-check fa-fw" style="color:#00FF00"></i>'.html_safe : '<i class="fa fa-close fa-fw" style="color:#FF0000"></i>'.html_safe %></td>
					<td>
						<p><%= link_to "Edit", edit_survey_path(survey), :class => "btn btn-info actions" %></p>
						<% if survey.survey_category != nil  && survey.questback_status.downcase == "active" %>
							<p><%= link_to "Send Push Notification", "#", :class => "btn btn-success actions", onclick: "showPushNotificationForm({ title: '#{survey.title}', id: #{survey.id} });" %></p>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
        </div>

        <div class="tab-pane" id="archived">
            	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>QuestBackID</th>
				<th>Category</th>
				<th>Duration</th>
				<th>Status</th>
				<th>Active</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @survey_archived.each do |survey| %>
				<tr>
					<td><%= link_to survey.title, survey %></td>
					<td><%= survey.survey_id %></td>
					<td>
						<% if survey.survey_category == nil %>
							UNASSIGNED
						<% else %>
							<%= survey.survey_category.name %>
							<div style="width:100px; height:20px; background-color:<%= survey.survey_category.color %>">&nbsp;</div>
							<% end %>
					</td>
					<td><%= survey.duration %></td>
					<td><%= survey.questback_status %></td>
					<td><%= survey.active ? '<i class="fa fa-check fa-fw" style="color:#00FF00"></i>'.html_safe : '<i class="fa fa-close fa-fw" style="color:#FF0000"></i>'.html_safe %></td>
					<td>
						<p><%= link_to "Edit", edit_survey_path(survey), :class => "btn btn-info actions" %></p>
						<% if survey.survey_category != nil  && survey.questback_status.downcase == "active" %>
							<p><%= link_to "Send Push Notification", "#", :class => "btn btn-success actions", onclick: "showPushNotificationForm({ title: '#{survey.title}', id: #{survey.id} });" %></p>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
        </div>

        <div class="tab-pane" id="closing">
         <table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>QuestBackID</th>
				<th>Category</th>
				<th>Duration</th>
				<th>Status</th>
				<th>Active</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @survey_closing.each do |survey| %>
				<tr>
					<td><%= link_to survey.title, survey %></td>
					<td><%= survey.survey_id %></td>
					<td>
						<% if survey.survey_category == nil %>
							UNASSIGNED
						<% else %>
							<%= survey.survey_category.name %>
							<div style="width:100px; height:20px; background-color:<%= survey.survey_category.color %>">&nbsp;</div>
							<% end %>
					</td>
					<td><%= survey.duration %></td>
					<td><%= survey.questback_status %></td>
					<td><%= survey.active ? '<i class="fa fa-check fa-fw" style="color:#00FF00"></i>'.html_safe : '<i class="fa fa-close fa-fw" style="color:#FF0000"></i>'.html_safe %></td>
					<td>
						<p><%= link_to "Edit", edit_survey_path(survey), :class => "btn btn-info actions" %></p>
						<% if survey.survey_category != nil  && survey.questback_status.downcase == "active" %>
							<p><%= link_to "Send Push Notification", "#", :class => "btn btn-success actions", onclick: "showPushNotificationForm({ title: '#{survey.title}', id: #{survey.id} });" %></p>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
        </div>

        <div class="tab-pane" id="finished">
             <table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>QuestBackID</th>
				<th>Category</th>
				<th>Duration</th>
				<th>Status</th>
				<th>Active</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @survey_finished.each do |survey| %>
				<tr>
					<td><%= link_to survey.title, survey %></td>
					<td><%= survey.survey_id %></td>
					<td>
						<% if survey.survey_category == nil %>
							UNASSIGNED
						<% else %>
							<%= survey.survey_category.name %>
							<div style="width:100px; height:20px; background-color:<%= survey.survey_category.color %>">&nbsp;</div>
							<% end %>
					</td>
					<td><%= survey.duration %></td>
					<td><%= survey.questback_status %></td>
					<td><%= survey.active ? '<i class="fa fa-check fa-fw" style="color:#00FF00"></i>'.html_safe : '<i class="fa fa-close fa-fw" style="color:#FF0000"></i>'.html_safe %></td>
					<td>
						<p><%= link_to "Edit", edit_survey_path(survey), :class => "btn btn-info actions" %></p>
						<% if survey.survey_category != nil  && survey.questback_status.downcase == "active" %>
							<p><%= link_to "Send Push Notification", "#", :class => "btn btn-success actions", onclick: "showPushNotificationForm({ title: '#{survey.title}', id: #{survey.id} });" %></p>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
        </div>
    </div>
</div>


<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $('#tabs').tab();
    });
</script>    
</div> <!-- container -->

app/views/surveys/_tabs.html.erb
<div class="page-tabs">
	<ul class="nav nav-tabs" role="tablist">

		<% if active == :surveys %><li class="active"><% else %><li><% end %>
			<%= link_to "Surveys", surveys_path %>
		</li>

		<% if active == :survey || active == :edit %>
			<% if active == :survey %><li class="active"><% else %><li><% end %>
				<%= link_to "Survey", survey_path %>
			</li>
			<% if active == :edit %><li class="active"><% else %><li><% end %>
				<%= link_to "Edit", edit_survey_path %>
			</li>
		<% end %>

	</ul>
</div>

app/views/surveys/edit.html.erb
<%= render "tabs", :active => :edit %>

<h2>Survey: <%= @survey.title %></h2>

<%= render 'form' %>


app/views/surveys/index.html.erb
<%= render "tabs", :active => :surveys %>

<br>

    <%= form_tag(surveys_path, :method => "get", style: 'float:right') do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Surveys", class: 'form-control', style: 'width:300px; display: inline-block;' %>
    <%= submit_tag "Search", :title => nil, class: 'form-control', style: 'width:90px; display: inline-block' %>
<% end %>

<%= link_to "Reload Active Surveys", reload_surveys_path(active: true), :remote => true, :class => "btn btn-info", :id => "reload-active-button", :style => "display:#{@reload_in_progress ? 'none' : 'inline-block'};" %>
	<p id="reloading-text" <%= @reload_in_progress ? "" : "hidden"%> >Reloading QuestBack Surveys...</p>
    <%= @reload_in_progress ? @reload_status : "" %>

<br><br>

<div class="list-group surveys-table">
	<%= render :partial => 'table' %>
</div>

<%= render 'layouts/modal' %>

app/views/surveys/reload.js.erb
$("#reloading-text").show();
$("#reload-button").hide();
$("#reload-active-button").hide();

app/views/surveys/show.html.erb
<%= render "tabs", :active => :survey %>

<div class="list-group">

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Title
		</div>
		<div class="list-group-item-text">
			<%= @survey.title %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			QuestBack ID
		</div>
		<div class="list-group-item-text">
			<%= @survey.survey_id %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Created Time
		</div>
		<div class="list-group-item-text">
			<%= @survey.created_time %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Start Time
		</div>
		<div class="list-group-item-text">
			<%= @survey.start_time %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			End Time
		</div>
		<div class="list-group-item-text">
			<%= @survey.end_time %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Bonus Points
		</div>
		<div class="list-group-item-text">
			<%= @survey.bonus_points %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Duration
		</div>
		<div class="list-group-item-text">
			<%= @survey.duration %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Survey Category
		</div>
		<div class="list-group-item-text">
			<% if @survey.survey_category == nil %>
				UNASSIGNED
			<% else %>
				<%= @survey.survey_category.name %>
				<div style="width:100px; height:20px; background-color:<%= @survey.survey_category.color %>">&nbsp;</div>
			<% end %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Registration Survey ?
		</div>
		<div class="list-group-item-text">
			<%= @survey.registration_survey %>
		</div>
	</div>

</div>