config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'statistics#index'

  namespace :api, :defaults => { :format => :json } do
    resources :surveys do
      collection do
        get :completed
        get :profile
      end
      get :is_active, on: :member
    end
    resources :auth do
      post :login, on: :collection
      post :logout, on: :collection
      post :facebook, on: :collection
      post :password_reset, on: :collection
    end
    resources :profile do
      patch :change, on: :collection
      post :avatar, on: :collection
      post :refer_a_friend, on: :collection
    end
    resources :mappings do
      get :masterdata, on: :collection
    end
    resources :register
    resources :push_notification_credentials
    resources :faqs
    resources :quick_polls do
      get :results, on: :member
      get :completed, on: :collection
    end
    resources :geofences do
      post :logs, on: :collection
    end
    resources :log
    resources :vpn_studies do
      collection do
        get :active
        get :completed
        get :cancelled
        get :connected
      end
      member do
        get :is_active
      end
    end
    resources :vpn_study_credentials do
      post  :download, on: :collection
      post  :activate, on: :collection
      post  :disconnect, on: :collection
      post  :complete, on: :collection
      get   :completed, on: :collection
    end
    resources :statistics do
      get :panelists, on: :collection
    end
    resources :device_metadata
  end

  resources :panelists do
    get :export, on: :collection
    get :sync_last_accessed, on: :collection
    get :autocomplete_panelist_email, on: :collection
    resources :push_notification_credentials do
      get :test, on: :member
    end
  end
  resources :settings
  resources :profile_variables
  resources :users
  resources :master_data_descriptions do
    get :reload, on: :collection
  end
  resources :mail_templates do
    get :reload, on: :collection
  end
  resources :survey_categories
  resources :surveys do
    get   :reload, on: :collection
    post  :send_notifications, on: :member
    get   :show_push_notification_form, on: :member
  end
  resources :profile_surveys
  resources :faqs
  resources :quick_polls do
    get :send_notifications, on: :member
    get :autocomplete_quick_poll_title, on: :collection
  end
  resources :quick_poll_responses do
    get :export, on: :collection
  end
  resources :geofences do
    get :export, on: :collection
    get :info, on: :collection
  end
  resources :geofence_logs do
    post  :export, on: :collection
    get   :panelist_logs, on: :collection
  end
  resources :geofence_groups do
    get   :reload_apps, on: :collection
    get   :map, on: :member
    get   :export, on: :collection
    post  :status_update, on: :member
    get :autocomplete_geofence_group_name, on: :collection
  end
  resources :samples do
    get :reload, on: :collection
  end
  resources :questback_groups do
    get :reload, on: :collection
    get :search, on: :collection
    get :autocomplete_questback_group_name, on: :collection
  end
  resources :geofence_collections do
    post  :import, on: :collection
    get   :upload, on: :collection
  end
  resources :quick_poll_stats do
    get :update_stats, on: :collection
  end
  resources :vpn_studies do
    member do
      get :send_notifications
      get :reload_data
      get :deactivate
    end
    get :autocomplete_vpn_study_name, on: :collection
  end
  resources :usage_study_access_logs do
    post :export, on: :collection
  end
  resources :usage_study_users do
    get :access_logs, on: :member
    get :export, on: :collection
  end
  resources :router_managements do
    post  :disconnect, on: :collection
    post  :sync, on: :collection
    get   :convert_ip_address, on: :collection
  end
  resources :ssl_decryption_hosts do
    post :sync, on: :collection
  end
  resources :vpn_bandwidth_usages do
    get :export, on: :collection
  end
  resources :device_metadata do
    get :panelist, on: :collection
  end
  resources :log_exports do
    get :export, on: :collection
    get :download, on: :member
  end
  resources :geofence_log_exports do
    get :download, on: :member
  end
  resources :vpn_managements do
    get :vpn_speed_test, on: :collection
  end
  resources :geofence_uploads do
    get :export_template, on: :collection
  end
  resources :bart_settings do
    get :export_csv_file, on: :collection
  end
  resources :panelist_stats do
  end

  resources :admin
  resources :push_notification_logs
  resources :statistics
  resources :panelist_sync_logs
  resources :vpn_routes
  resources :decrypt_hosts
  resources :vpn_page_monitorings
  resources :vpn_page_monitoring_results
  resources :vpn_study_credentials
  resources :logs
  resources :bart_audit_logs

  get '*path' => redirect('/')








end

app/models/panelist.rb
require 'vpn_api'

class Panelist < ActiveRecord::Base
  include UrlBuilder
  include CsvBuilder
  include Searchable

  has_secure_password validations: false
  has_many :push_notification_credentials, :dependent => :destroy
  has_many :quick_poll_choices, through: :quick_poll_responses
  has_many :quick_poll_responses, :dependent => :destroy
  has_many :geofence_logs, dependent: :destroy
  has_and_belongs_to_many :samples

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  before_save   :create_access_token
  after_create  :generate_external_auth_code

  has_many :questback_group_users, :foreign_key => :uid, :primary_key => :uid, :class_name => "QuestbackGroupUser"
  has_many :questback_groups, through: :questback_group_users
  has_many :geofence_groups,  through: :questback_groups
  has_many :geofences,    through: :geofence_groups
  has_many :quick_polls,  through: :questback_groups
  has_many :vpn_studies,  through: :questback_groups
  has_many :vpn_study_credentials
  has_many :device_metadata
  has_many :bart_exclusions
  has_many :bart_audit_logs

  scope :ordered, -> { order("last_accessed desc") }
  scope :active_by_last_accessed_with_range, -> (start_date, end_date) { where(last_accessed: start_date..end_date) }

  def self.search(search)
  where("email LIKE ?", "%#{search}%") 
  end

  def to_s
    email
  end

  def self.active_between(start_date, end_date)
    where(last_accessed: start_date..end_date)
  end

  # def self.get_email(access_token)
  #   panelist = Panelist.find_by_access_token(access_token)
  #   !panelist.blank? && !panelist.expired? ? panelist.email : nil
  # end

  def completed_quick_polls
    quick_poll_choices.map(&:quick_poll).uniq if quick_poll_choices
  end

  def available_quick_polls
    available_polls       = quick_polls.activities.active.with_quick_poll_questions - completed_quick_polls
    polls = {
      'quick_polls' => available_polls.map do |quick_poll|
        quick_poll.poll_info
      end
    }
    return polls
  end

  def get_redeem_url
    UrlBuilder::build_url(Setting.first.qb_hostname, "/survey_redeem.php", "login_code=#{external_auth_panelist_code}")
  end

  # Don't remove this. A fix in EFS side is on going for this implementation
  # def refer_a_friend(refer_email: nil, name: nil)
  #   refer_promotion_id = Setting.first.refer_promotion_id

  #   params = {
  #     promotion_id: refer_promotion_id,
  #     email: refer_email,
  #     panelist_id: uid
  #   }

  #   qb = ::Questback.new(email)
  #   qb.tell_a_friend(params)
  # end

  def refer_a_friend(refer_email: nil, name: nil)
    app_setting     = Setting.first
    base_url        = UrlBuilder::build_url(app_setting.qb_hostname, "/my_refer.php")
    post_url        = URI.parse(base_url)
    post_url.query  = URI.encode_www_form(
      ch_stage_module_my_refer_2: 'execute',
      ch_header_module_my_refer_2: name,
      ch_email_module_my_refer_2: refer_email,
      ch_campaign_id_module_my_refer_2: app_setting.refer_promotion_id,
      login_code: external_auth_panelist_code,
      frmnd: 'my_refer'
    )

    HTTParty.post(post_url)
  end

  def self.reset_password(email)
    post_url = UrlBuilder::build_url(Setting.first.qb_hostname, '/password_recover.php', 'ch_stage_RECOVERY=sendticket_email_check&frmnd=password_recover')
    uri = URI.parse(post_url)

    http = Net::HTTP.new(uri.host, uri.port)

    request = Net::HTTP::Post.new(uri.request_uri, {"Accept-Encoding" => ""})
    params = {
      :ch_email_RECOVERY => email,
      :frmnd => 'password_recover'
    }
    request.set_form_data(params)
    http.request(request)
  end

  def generate_external_auth_code
    qb = ::Questback.new(email)
    panelist_code = nil

    if external_auth_code.nil?
      auth_code = SecureRandom.uuid
      qb.create_external_auth(auth_code)
      self.external_auth_code = auth_code
      panelist_code = qb.get_external_auth_pcode(external_auth_code)
    else
      if external_auth_panelist_code.nil?
        panelist_code = qb.get_external_auth_pcode(external_auth_code)
      else
        panelist_code = external_auth_panelist_code
      end
    end

    self.external_auth_panelist_code = panelist_code
    self.save!
  end

  def geofences_without_completed_survey
    geofences.where(geofence_group_id: allowed_geofence_group_ids)
  end

  def remove_existing_push_notification_credentials(service)
    notification_service = service.eql?('apn') ? "apple_devices" : "android_devices"
    notification_service = "all" if service.nil?

    credentials = push_notification_credentials.send(notification_service.to_sym)
    credentials.destroy_all
  end

  def send_device_notification(survey_id:)
    unless is_included_in_completed_survey?(survey_id)
      push_notification_credentials.each do |push_notification_credential|
        push_notification_credential.send_push_notification(survey_id: survey_id)
      end
    end
  end

  def has_apn?
    push_notification_credentials.apple_devices.any?
  end

  def has_gcm?
    push_notification_credentials.android_devices.any?
  end

  def csv_values
    [
      id,
      access_token,
      email,
      last_accessed,
      uid,
      created_at,
      activated,
      external_auth_code,
      external_auth_panelist_code,
      has_apn?,
      has_gcm?
    ]
  end

  def has_active_vpn_study?
    vpn_study_credentials.active.any?
  end

  def active_vpn_study
    active_vpn_study_credential = vpn_study_credentials.active.last
    active_vpn_study_credential.vpn_study.attributes_with_values
  end

  def available_vpn_studies
    completed_and_cancelled_vpn_study_ids   = vpn_study_credentials.completed_and_cancelled.pluck(:vpn_study_id)
    available_vpn_studies                   = vpn_studies.active.where.not(id: completed_and_cancelled_vpn_study_ids)

    available_vpn_studies
  end

  def completed_vpn_studies
    vpn_study_credentials.complete.map{ |vpn_study_credential| vpn_study_credential.vpn_study.attributes_with_values}
  end

  def cancelled_vpn_studies
    vpn_study_credentials.cancelled.map{ |vpn_study_credential| vpn_study_credential.vpn_study.attributes_with_values}
  end

  def create_vpn_study_credential(vpn_study_credential)
    vpn_study_api_client = VpnApi.new(panelist_id:  id,
                                      vpn_study_id: vpn_study_credential[:vpn_study_id],
                                      type:         vpn_study_credential[:type])
    vpn_study_api_client.create_config
  end

  private
    def create_access_token
      if self.access_token.blank?
        self.access_token = SecureRandom.uuid
      end
    end

    def allowed_geofence_group_ids
      sample_survey_geofence_group_ids - (completed_survey_geofence_group_ids + completed_quick_poll_geofence_group_ids)
    end

    def completed_survey_geofence_group_ids
      completed_survey_ids = Survey.where(survey_id: completed_questback_surveys_ids).pluck(:id)
      geofence_groups.single.where(survey_id: completed_survey_ids).pluck(:id)
    end

    def completed_quick_poll_geofence_group_ids
      completed_quick_poll_ids = completed_quick_polls.map{ |completed_quick_poll| completed_quick_poll.id }
      geofence_groups.single.where(quick_poll_id: completed_quick_poll_ids).pluck(:id)
    end

    def sample_survey_geofence_group_ids
      active_survey_ids_from_sample = samples.map{ |sample| sample.survey_id if sample.survey && sample.survey.is_active_and_questback_active? }.compact
      geofence_groups.active.where(survey_id: [active_survey_ids_from_sample, nil]).pluck(:id)
    end

    def self.except_attributes
      %w(updated_at password_digest avatar_file_name avatar_content_type avatar_file_size avatar_updated_at)
    end

    def is_included_in_completed_survey?(survey_id)
      completed_questback_surveys_ids.include?(survey_id)
    end

    def completed_questback_surveys_ids
      questback             = Questback.new email
      completed_surveys     = questback.get_completed_surveys
      completed_surveys.nil? ? [] : completed_surveys.map{ |completed_survey| completed_survey['surveyId'].to_s }
    end

end

app/controllers/panelists_controller.rb
class PanelistsController < ApplicationController
  include CsvExport

  autocomplete :panelist, :email, extra_data: [:id], full: true, limit: 100

  before_action :authenticate_user!
  before_action :find_panelist, only: [:show,:destroy]

  def index
    @panelists  = Panelist.search(params[:search]).ordered.paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.js

    end
  end

  def show
  end

  def destroy
    @panelist.destroy
    redirect_to panelists_path
  end

  def export
    custom_attributes = ['has_apn?', 'has_gcm?']
    export_params = {
      records: Panelist.all,
      header: Panelist.csv_attributes(custom_attributes: custom_attributes)
    }
    send_data generate_csv_file(export_params), :filename => "panelist_export.csv", :type => "text/plain"
  end

  def sync_last_accessed
    PanelistsSyncLastAccessedJob.perform_later(user_id: current_user.id)
    redirect_to panelist_sync_logs_path, notice: "You've successfully execute the sync of panelists last accessed."
  end

  private

  def find_panelist
    @panelist = Panelist.find(params[:id])
  end

  def panelist_stats 
  end

end

app/helpers/panelists_helper.rb
module PanelistsHelper
  def active_panelist(range=nil)
    start_date    = range.nil? ? Time.zone.now : (Time.zone.now - 1.send(range))
    current_date  = Time.zone.now
    Panelist.active_between(start_date.beginning_of_day, current_date.end_of_day).count
  end
end

app/views/panelists/_table.html.erb

    <table class="table">
      <thead>
        <th>Email</th>
        <th>Access Token</th>
        <th>Questback UID</th>
        <th>Last Accessed</th>
      </thead>
      <tbody>
        <% @panelists.each do |panelist| %>
          <tr>
            <td class=<% panelist.activated ? '' : 'text-muted' %>>
              <%= link_to "#{panelist.email}", panelist, :class => panelist.activated ? '' : 'text-muted' %>
            </td>
            <td><%= panelist.access_token %></td>
            <td><%= panelist.uid %></td>
            <td><%= panelist.last_accessed %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <%= will_paginate @panelists %>



app/views/panelists/_tabs.html.erb
<div class="page-tabs">
	<ul class="nav nav-tabs" role="tablist">

		<% if active == :panelists %><li class="active"><% else %><li><% end %>
			<%= link_to "Panelists", panelists_path %>
		</li>

		<% if active == :panelist_stats %><li class="active"><% else %><li><% end %>
			<%= link_to "Statistics", panelist_stats_path %>
		</li>

		<% if active == :panelist %>
			<li class="active">
				<%= link_to "Panelist", panelists_path %>
			</li>
		<% end %>


	</ul>
</div>

app/views/panelists/index.html.erb
<%= render "tabs", :active => :panelists %>

<br>

    <%= link_to "Export to CSV", export_panelists_path, :class => "btn btn-info" %>

<br><br>

    <%= form_tag(panelists_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Panelists", class: 'form-control', style: 'width:300px; display: inline-block' %>
    <%= submit_tag "Search", :email => nil, class: 'form-control', style: 'width:90px; display: inline-block' %>
<% end %>

<br>

<%= render 'table' %>


app/views/panelists/index.js.erb
$("#panelistTable").html("<%= escape_javascript(render partial: 'table') %>");

app/views/panelists/show.html.erb
<%= render "tabs", :active => :panelist %>

<h1>Panelist</h1>

<div class="list-group">



	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Email
		</div>
		<div class="list-group-item-text">
			<%= @panelist.email %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Access Token
		</div>
		<div class="list-group-item-text">
			<%= @panelist.access_token %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Avatar
		</div>
		<div class="list-group-item-text">
			<% if @panelist.avatar_file_name != nil %>
				<%= image_tag @panelist.avatar.url %>
			<% end %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Last Accessed
		</div>
		<div class="list-group-item-text">
			<%= @panelist.last_accessed %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Activated
		</div>
		<div class="list-group-item-text">
			<%= @panelist.activated %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Questback UID
		</div>
		<div class="list-group-item-text">
			<%= @panelist.uid %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Push Notification Credentials
		</div>

		<div class="list-group-item-text">
			<% @panelist.push_notification_credentials.each do |pnc| %>
				<%= link_to panelist_push_notification_credential_path(@panelist, pnc) do %>
					<p><strong><%= pnc.notification_service.upcase %></strong> - <%= pnc.token %></p>
				<% end %>
			<% end %>
		</div>
	</div>

	<div class="list-group-item">
		<div class="list-group-item-heading text-muted">
			Questback Groups
		</div>

		<div class="list-group-item-text">
			<ul>
				<% @panelist.questback_groups.each do |group| %>
					<li><%= link_to group.name, group %></li>
				<% end %>
			</ul>
		</div>
	</div>

</div>